version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: database-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin


